
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
    application:
        name: gsiteCustomer
    jackson:
        serialization.write_dates_as_timestamps: false
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

server:
    session:
        cookie:
            http-only: true

info:
    project:
        version: #project.version#

payment:
    paypal:
        mode: sandbox
        clientId: ATmfnJTpXRBIu9wwaUoEKjj6alLPhdhL4zKVmK5HgpDZkGbs8Z1Pna_j_ct5_2DkS8mlQ3bo2V9tk_dr
        clientSecret: EIZoxGT6GpHop3JoxsXwvyS-UiGL4yaTwF-aB4XtQ89xy-XkbEn8RpYPSOM_rrL5B_eNriTyIOtVOutq
        cancelUrl: http://localhost:9000/website-payment/
        returnUrl: http://localhost:9000/website-payment/

storage:
    url:
        image: /
# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: gsiteCustomer@localhost
    swagger:
        default-include-pattern: /api/.*
        title: gsiteCustomer API
        description: gsiteCustomer API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
    ribbon:
        display-on-active-profiles: dev

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

application:
