version: '2'
services:
    gsitecustomer-app:
        image: gsitecustomer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://gsitecustomer-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=gsiteCustomer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    gsitecustomer-mongodb:
        extends:
            file: mongodb.yml
            service: gsitecustomer-mongodb
